### ISSUE TITLE
повторное копирование плота

### ISSUE THREAD

**Issue by madest13** [setar/chia_plots_mover#1]
настройки
одна папка источник - 3 папки назначения
скрипт запускается каждые 10 минут

если идет копирование в первую папку, за 10 минут не успевает скопироваться, запускается процесс копирования во вторую папку, т.е. одновременно копируется 2 файла в разные папки назначения

в первую папку заканчивается процесс переноса и исходный файл удаляется, во вторую идет копирование..
запускается скрипт снова, и начинает копировать файл, который уже переносится во вторую папку назначения, просто он еще не успел докопироваться.. после этого в первой папке назначения докопированый файл не переименовывается и не удаляется *.space файл. при проверке плотов появляются ошибки одинаковых файлов в папке назначения

**Comment by setar** [comment]
Абсолютно верно. 
Я просто остановил тут модернизацию скрипта, он вошел в состав утилит для фарминга.
там уже все эти нюансы учтены: 
делается отметка о копировании в папке источника и контроль времени (в планах так же убивание по pid зависших процессов копирования, но пока не проходит передача пид в файл, сделаю ближайшие дни)

https://github.com/setar/chia-farm-tools
https://github.com/setar/chia-farm-tools/blob/main/chia-scripts/chia_plots_mover.sh

сейчас сделаю отметку о завершении этого репо.

**Comment by setar** [comment]
Script permanent moved in to 
https://github.com/setar/chia-farm-tools
https://github.com/setar/chia-farm-tools/blob/main/chia-scripts/chia_plots_mover.sh
